[target.thumbv7em-none-eabihf]
rustflags = [
    # CPU is Cortex-M4 (STM32WB55)
    "-C", "target-cpu=cortex-m4",

    # Size optimizations
    "-C", "panic=abort",
    "-C", "lto=true",
    "-C", "linker-plugin-lto=true",
    "-C", "embed-bitcode=true",
    "-C", "opt-level=1",

    # Linker flags for relocatable binary
    "-C", "link-args=--script=flipperzero-rt.ld --Bstatic --relocatable",
]

[build]
target = "thumbv7em-none-eabihf"
